### ISSUE TITLE
release changes -to_cherrypick panics

### ISSUE THREAD

**Issue by tchap** [salsaflow/salsaflow#112]
```
[RUN]      Fetch the stories associated with the current release
[RUN]      Fetch data from Pivotal Tracker
[RUN]      Collect the story changes
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x40 pc=0x12ae48]

goroutine 1 [running]:
github.com/salsaflow/salsaflow/changes.sortWrapperSlice.Less(0xc2081e6780, 0x4c, 0x4c, 0x48, 0x0, 0x112401)
    /home/ubuntu/workspace/src/github.com/salsaflow/salsaflow/changes/change_group.go:119 +0x78
github.com/salsaflow/salsaflow/changes.(*sortWrapperSlice).Less(0xc20813b980, 0x48, 0x0, 0xc20813b001)
    <autogenerated>:5 +0xb5
sort.reverse.Less(0x8c4bb8, 0xc20813b980, 0x0, 0x48, 0x8c4b01)
    /usr/local/go/src/sort/sort.go:211 +0x4c
sort.(*reverse).Less(0xc2082d8510, 0x0, 0x48, 0x1)
    <autogenerated>:21 +0xb3
sort.doPivot(0x8c4bf0, 0xc2082d8510, 0x0, 0x4c, 0xc20813b980, 0x4c)
    /usr/local/go/src/sort/sort.go:138 +0x231
sort.quickSort(0x8c4bf0, 0xc2082d8510, 0x0, 0x4c, 0xd)
    /usr/local/go/src/sort/sort.go:173 +0xa9
sort.Sort(0x8c4bf0, 0xc2082d8510)
    /usr/local/go/src/sort/sort.go:200 +0x7b
github.com/salsaflow/salsaflow/changes.SortStoryChanges(0xc2081e6500, 0x4c, 0x4c, 0xc208294000, 0x50, 0x50, 0x0, 0x0, 0x0)
    /home/ubuntu/workspace/src/github.com/salsaflow/salsaflow/changes/change_group.go:96 +0x524
github.com/salsaflow/salsaflow/commands/release/changes.runMain(0x0, 0x0)
    /home/ubuntu/workspace/src/github.com/salsaflow/salsaflow/commands/release/changes/command.go:137 +0x92b
github.com/salsaflow/salsaflow/commands/release/changes.run(0x7bbf20, 0xc20800a030, 0x0, 0x0)
    /home/ubuntu/workspace/src/github.com/salsaflow/salsaflow/commands/release/changes/command.go:72 +0x58
gopkg.in/tchap/gocli%2ev2.(*Command).Run(0x7bbf20, 0xc20800a030, 0x1, 0x1)
    /home/ubuntu/salsaflow/Godeps/_workspace/src/gopkg.in/tchap/gocli.v2/command.go:117 +0x2d1
gopkg.in/tchap/gocli%2ev2.(*Command).Run(0x7bbe40, 0xc20800a020, 0x2, 0x2)
    /home/ubuntu/salsaflow/Godeps/_workspace/src/gopkg.in/tchap/gocli.v2/command.go:124 +0x437
gopkg.in/tchap/gocli%2ev2.(*Command).Run(0xc208035e10, 0xc20800a010, 0x3, 0x3)
    /home/ubuntu/salsaflow/Godeps/_workspace/src/gopkg.in/tchap/gocli.v2/command.go:124 +0x437
main.main()
    /home/ubuntu/workspace/src/github.com/salsaflow/salsaflow/main.go:61 +0x3a2

goroutine 5 [syscall]:
os/signal.loop()
    /usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
    /usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 7 [chan receive]:
main.catchSignals(0xc208066600)
    /home/ubuntu/workspace/src/github.com/salsaflow/salsaflow/main.go:65 +0x40
created by main.main
    /home/ubuntu/workspace/src/github.com/salsaflow/salsaflow/main.go:58 +0x340

goroutine 81 [syscall, locked to thread]:
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1
```

**Comment by tchap** [comment]
Released as a hotfix in `0.17.1`
